### ISSUE TITLE
Error in 'make requirements' 

### ISSUE THREAD

**Issue by htkgithub** [gnocchiflette/NTU-RGB-D#26]
Hi,

I couldn't install "matplotlib 3.0.2" while running make requirements command.

It says "ERROR: Could not find a version that satisfies the requirement matplotlib==3.0.2" (from versions: .......3.0.2, 3.0.3,.....).

I have tried lots of things to solve.

Is it because the python version I used (Python 3.8.12)?

Thank you for the great work and your help in advance.

**Comment by adeboissiere** [comment]
Hi, thanks for the interest, the code is likely outdated. However, you can try to erase the version when installing matplotlib. 
So rewriting matplotlib==3.0.2 to matplotlib in requirements.txt
Also, I believe the code was developed in python 3.7 but you should be able to make it work with python 3.8 with minimal efforts.
Hope that helps.

**Comment by htkgithub** [comment]
Hi, thank you for your help.

31 Oca 2022 Pzt 03:50 tarihinde Alban Main de Boissiere <
***@***.***> şunu yazdı:
